#!/usr/bin/env node
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { performance } from 'node:perf_hooks';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const require = createRequire(import.meta.url);
const indexModulePath = join(repoRoot, 'dist-electron', 'vault-index.js');

function parseSizes() {
  const raw = process.argv.find((arg) => arg.startsWith('--sizes='))?.slice('--sizes='.length)
    ?? process.env.CLASSNOTES_PERF_SIZES
    ?? '100,1000,5000';
  return raw
    .split(',')
    .map((value) => Number(value.trim()))
    .filter((value) => Number.isInteger(value) && value > 0);
}

function formatBytes(bytes) {
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

async function createSyntheticVault(noteCount) {
  const root = await mkdtemp(join(tmpdir(), `classnotes-perf-${noteCount}-`));
  await mkdir(join(root, '.obsidian'), { recursive: true });
  await mkdir(join(root, 'Papers'), { recursive: true });
  await mkdir(join(root, 'Math', 'notes'), { recursive: true });
  await mkdir(join(root, 'History', 'notes'), { recursive: true });
  await writeFile(join(root, 'Papers', 'refs.bib'), '@article{seed2026,title={Seed}}\n', 'utf-8');

  const writes = [];
  for (let i = 0; i < noteCount; i += 1) {
    const subject = i % 2 === 0 ? 'Math' : 'History';
    const rel = join(subject, 'notes', `Note-${String(i).padStart(5, '0')}.md`);
    const link = i > 0 ? `[[Note-${String(i - 1).padStart(5, '0')}]]` : '[[Index]]';
    const body = [
      '---',
      `title: Note ${i}`,
      `tags: [perf, subject-${subject.toLowerCase()}]`,
      `bibkey: perf${i}`,
      i % 3 === 0 ? `doi: 10.1000/perf.${i}` : '',
      '---',
      '',
      `# Note ${i}`,
      '',
      `Synthetic benchmark note ${i}. ${link}`,
      'This file is generated by scripts/perf-vault.mjs and contains no user data.',
      '',
    ].join('\n');
    writes.push(writeFile(join(root, rel), body, 'utf-8'));
    if (writes.length >= 250) {
      await Promise.all(writes.splice(0));
    }
  }
  await Promise.all(writes);
  return root;
}

async function measureOne(noteCount, vaultIndex) {
  const vault = await createSyntheticVault(noteCount);
  const indexDir = await mkdtemp(join(tmpdir(), `classnotes-index-perf-${noteCount}-`));
  try {
    vaultIndex.setVaultIndexDirectoryForTests(indexDir);
    const before = process.memoryUsage().rss;
    const started = performance.now();
    const index = await vaultIndex.rebuildVaultIndex(vault);
    const buildMs = performance.now() - started;

    const searchStarted = performance.now();
    const hits = index.files.filter((file) => file.searchText.includes('subject-math')).length;
    const searchMs = performance.now() - searchStarted;
    const after = process.memoryUsage().rss;

    return {
      notes: noteCount,
      indexedFiles: index.files.length,
      buildMs: Math.round(buildMs),
      searchMs: Number(searchMs.toFixed(2)),
      hits,
      rssDelta: after - before,
    };
  } finally {
    vaultIndex.setVaultIndexDirectoryForTests(null);
    await rm(vault, { recursive: true, force: true });
    await rm(indexDir, { recursive: true, force: true });
  }
}

async function main() {
  if (!existsSync(indexModulePath)) {
    console.error('dist-electron/vault-index.js が見つかりません。先に npm run build を実行してください。');
    process.exit(1);
  }
  const sizes = parseSizes();
  if (sizes.length === 0) {
    console.error('有効な --sizes=100,1000 の形式を指定してください。');
    process.exit(1);
  }

  const vaultIndex = require(indexModulePath);
  const results = [];
  for (const size of sizes) {
    const result = await measureOne(size, vaultIndex);
    results.push(result);
    console.log(
      [
        `notes=${result.notes}`,
        `indexed=${result.indexedFiles}`,
        `build=${result.buildMs}ms`,
        `search=${result.searchMs}ms`,
        `rssDelta=${formatBytes(result.rssDelta)}`,
      ].join(' ')
    );
  }

  console.log('\nJSON');
  console.log(JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
